version: "3"

services:
    influxdb:
        image: influxdb:latest
        container_name: ${CONTAINER_PREFIX}_influxdb
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=${TIMEZONE}
        ports:
            - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
        volumes:
            - ./influxdb:/var/lib/influxdb
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - backend
            - frontend
    telegraf:
        image: docker.io/telegraf:latest
        container_name: ${CONTAINER_PREFIX}_telegraf
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=${TIMEZONE}
        links:
            - influxdb
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mount the Telegraf configuration file
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - backend
    grafana:
        image: grafana/grafana:latest
        container_name: ${CONTAINER_PREFIX}_grafana
        environment:
          - TZ=${TIMEZONE}
        ports:
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - influxdb
        volumes:
            - ./grafana/data:/var/lib/grafana
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - frontend
        user: "0"

networks:
    backend:
    frontend: